#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# The two parameters are files that contain version numbers.
# If the versions differ or the comparision failed, exit with status 1,
# and open a comparison session in Beyond Compare if it's available.
abort_if_versions_differ () {
	.git_hooks/versions_consistent.py "$1" "$2" >/dev/null
	if [ $? -ne 0 ]; then
		echo Versions in "$1" and "$2" may be different ... aborting commit
		if [ $(which bcompare) ]; then
			# bcompare is available.
			/usr/bin/bcompare "$1" "$2" &
		fi
		exit 1
	fi
}

# The two parameters are files or directories.
# If their contents are different, exit with status 1,
# and open a comparison session in Beyond Compare if it's available.
abort_if_different () {
	/usr/bin/diff --recursive "$1" "$2" >/dev/null
	if [ $? -ne 0 ]; then
		echo "$1" differs from "$2" ... aborting commit
		if [ $(which bcompare) ]; then
			# bcompare is available.
			/usr/bin/bcompare "$1" "$2" &
		fi
		exit 1
	fi
}

# Perform consistency checks.
echo Performing consistency checks.
abort_if_versions_differ "version.py" "addons/radial_progress/plugin.cfg"
abort_if_different "version.py" "addons/radial_progress/version.py"
abort_if_different "addons/" "demo/addons/"
abort_if_different "LICENSE" "addons/radial_progress/LICENSE"

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
